[local_metas]
sync = true    
read_only = true
nick_name = ''

[metas]
add_new_opts = false
cmpnts_change = false
strict_namedtuples = true
strict_opts = true
sDNAUISpec = 'sDNAUISpec'
runsdnacommand = 'runsdnacommand' 
sDNA_search_paths  = ['C:\Program Files (x86)\sDNA']
update_path = true
##########################################################################
#
# Override for sDNA_ToolWrapper
#                        
show_all = true
###############################################################################
#Abbreviation = Tool Name
#[metas.name_map]
#Tool Name = Category Name                       
#[metas.categories]               
###############################################################################

[options]
###########################################################################
#System
#
platform = 'NT' # in {'NT','win32','win64'} only supported for now
encoding = 'utf-8'
#
###########################################################################
#
# Automatic tool insertion rules ('smart' tools)
#
auto_get_Geom = true
auto_read_Usertext = true
auto_write_Shp = true
auto_read_Shp = true
#auto_parse_data = false  # not used.  ObjectsRecolourer parses if req anyway
auto_plot_data = true
###########################################################################
#
# Overrides for .custom.logging_wrapper
#
# path = file_to_work_from  
# working_folder = 
# logger_name = 
# log_file = 
logs_dir = 'logs'
log_file_level = 'DEBUG'
log_console_level = 'DEBUG'
#
##########################################################################
#
# Overrides for sDNA_ToolWrapper
#
python_exe = 'C:\Python27\python.exe' 
prepped_fmt = '{name}_prepped'
output_fmt = '{name}_output'   
del_after_sDNA = false
strict_no_del = false # Also in ShapefileReader
###########################################################################    
#
# Overrides for RhinoObjectsReader
#
selected = false
#layer = ''
merge_subdicts = true
#
#
###########################################################################
#
#     Shapefiles
#     Application specific overrides for .custom.pyshp_wrapper
#
shape_type = 'POLYLINEZ' # Also in RhinoObjectsReader, ShapefileWriter
locale = ''  # '' => User's own settings.  Also in DataParser
             # e.g. 'fr', 'cn', 'pl'. IETF RFC1766,  ISO 3166 Alpha-2 code
             # Used for locale.setlocale(locale.LC_ALL,  options.locale)

#
# coerce_and_get_code
decimal = true
precision = 12
max_dp = 4 # decimal places
yyyy_mm_dd = false
keep_floats = true
use_memo = false # Use the 'M' field code in Shapefiles for uncoerced data
#
# get_filename
overwrite_shp = true
max_new_files = 20
suppress_warning = true     
dupe_file_key_str = '{name}_({number})'
#
# ensure_correct & write_iterable_to_shp
extra_chars = 2
#
# write_iterable_to_shp
field_size = 30
cache_iterable= false
uuid_field = 'Rhino3D_' # 'object_identifier_UUID_'  
# also in ShapefileReader, UsertextWriter  
uuid_length = 36 # 32 in 5 blocks (2 x 6 & 2 x 5) with 4 seperator characters.
num_dp = 10 # decimal places
min_sizes = true
#
###########################################################################
#
# Overrides for ShapefileWriter
#
input_key_str = 'sDNA input name={name} type={fieldtype} size={size}'
#30,000 characters tested.
# output_shp = 
###########################################################################
#
# Overrides for ShapefileReader
#
new_geom = true
del_after_read = false                 
sDNA_names_fmt = '{name}.shp.names.csv'  
###########################################################################   
#         
# Overrides for UsertextWriter
#   
output_key_str = 'sDNA output={name} run time={datetime}'  
#30,000 characters tested.
overwrite_UserText = true
max_new_keys = 6
suppress_overwrite_warning = false
dupe_key_suffix = '_{}'
###########################################################################   
#         
# Overrides for DataParser
#   
field = 'BtEn'
#plot_max = 
#plot_min = 
sort_data = false
base = 10 # base of log and exp spline, not of number representations
re_normaliser = 'linear' #['linear', 'exponential', 'logarithmic']
#
# Legend options
#
# class_bounds = 
# e.g. [2000000, 4000000, 6000000, 8000000, 10000000, 12000000]
num_classes = 7
class_spacing = 'quantile' 
first_leg_tag_str = 'below {upper}'
gen_leg_tag_str = '{lower} - {upper}' # also supports {mid_pt}
last_leg_tag_str = 'above {lower}'
num_format = '{:.5n}'
leg_frame = ''  # uuid of GH object
colour_as_class = false
exclude = false
suppress_small_classes_error = false
suppress_class_overlap_error = false
#
#
###########################################################################   
#         
# Overrides for ObjectsRecolourer
#   
#leg_extent =  # e.g. [xmin, ymin, xmax, ymax]
#bbox =  # e.g. [xmin, ymin, xmax, ymax] # used to auto make a legend frame 
Col_Grad = false
Col_Grad_num = 5
rgb_max = [155, 0, 0] #990000
rgb_min = [0, 0, 125] #3333cc
rgb_mid = [0, 155, 0] # guessed
line_width = 4 # milimetres? 
###########################################################################
#
# Options override system test field
#
message = 'Installation wide options from config.toml'

