[local_metas]
sync_to_shared_global_opts = true
read_from_shared_global_opts = true
#
[metas] 
add_in_new_options_keys = false
allow_components_to_change_type = true
typecheck_opts_namedtuples = true
typecheck_opts_fields = true
sDNAUISpec = 'sDNAUISpec'
runsdna = 'runsdnacommand'
#sDNA = (sDNAUISpec, runsdna)  # Read only.  Auto updates from above two.
sDNA_path = ''  # Read only.  Determined after loading sDNAUISpec to which ever below
                # it is found in.
                # after loading, assert opts['metas'].sDNA_path == dirname(opts['options'].UISpec.__file__)
sDNA_UISpec_path = 'C:\Program Files (x86)\sDNA\sDNAUISpec.py'
#sDNA_search_paths = [sDNA_UISpec_path, join(os.getenv('APPDATA'),'sDNA')]
#sDNA_search_paths += [join(os.getenv('APPDATA'), get_stem_and_folder(sDNA_search_paths[0])[1]) ]
auto_update_Rhino_doc_path = true

[options]
platform = 'NT' # in {'NT','win32','win64'} only supported for now
encoding = 'utf-8'
rhino_executable = 'C:\Program Files\Rhino 7\System\Rhino.exe'

Rhino_doc_path = ''  # tbc by loader
sDNA_prepare = 'C:\Program Files (x86)\sDNA\bin\sdnaprepare.py'
sDNA_integral = 'C:\Program Files (x86)\sDNA\bin\sdnaintegral.py'
python_exe = 'C:\Python27\python.exe' # Default installation path of Python 2.7.3 release (32 bit ?) http://www.python.org/ftp/python/2.7.3/python-2.7.3.msi
                                        # grouped from sDNA manual https://sdna.cardiff.ac.uk/sdna/wp-content/downloads/documentation/manual/sDNA_manual_v4_1_0/installation_usage.html    
####################################################################################
#Logging    
log_file_suffix = '_GHsDNA'
#log_file = __file__.rpartition('.')[0] + log_file_suffix + '.log'
#os.getenv('APPDATA'),'Grasshoppe','Libraries','GHsDNA','GHsDNA.log')
logs_subdirectory = 'logs'
tests_subdirectory = 'tests'
logger_file_level = 'DEBUG'
logger_console_level = 'DEBUG'
logger_custom_level = 'ERROR'

####################################################################################
#GDM
merge_Usertext_subdicts_instead_of_overwriting = true
use_initial_groups_if_too_many_in_list = true
use_initial_data_if_too_many_in_list = true
include_groups_in_gdms = false
####################################################################################
#Shapefiles
shp_file_shape_type = 'POLYLINEZ'
read_from_Rhino_if_no_shp_file = false
cache_iterable_when_writing_to_shp= false
shp_file_extension = '.shp' # file extensions are actually optional in PyShp, but just to be safe and future proof
supply_sDNA_file_names = true
shape_file_to_write_Rhino_data_to_from_GHsDNA = 'C:\Users\James\Documents\Rhino\Grasshopper\GHsDNA_shapefiles\t6.shp' # None means Rhino .3dm filename is used.
overwrite_shp_file = true
overwrite_UserText = true
duplicate_UserText_key_suffix = '_{}'
prepped_shp_file_suffix = "_prepped"
output_shp_file_suffix = "_output"
duplicate_file_name_suffix = '_({})' # Needs to contain a replacement field {} that .format can target.  No f strings in Python 2.7 :(
max_new_files_to_make = 20
suppress_overwrite_warning = true     
uuid_shp_file_field_name = 'Rhino3D_' # 'object_identifier_UUID_'     
uuid_length = 36 # 32 in 5 blocks (2 x 6 & 2 x 5) with 4 seperator characters.
calculate_smallest_field_sizes = true
delete_shapefile_after_reading = false
global_shp_file_field_size = 30
global_shp_number_of_decimal_places = 10
shp_file_field_size_num_extra_chars = 2
enforce_yyyy_mm_dd = false
use_str_decimal = true
do_not_convert_floats = true
decimal_module_prec = 12
shp_record_max_decimal = 4
####################################################################################
#Writing and Reading Usertext to/from Rhino
create_new_groups_layer_from_shapefile = false
max_new_UserText_keys_to_make = 20
#
#
rhino_user_text_key_format_str_to_read = 'sDNA input name={name} type={fieldtype} size={size}'  #30,000 characters tested!
sDNA_output_user_text_key_format_str_to_read = 'sDNA output={name} run time={datetime}'  #30,000 characters tested!
####################################################################################
#Plotting results
sDNA_output_abbrev_to_graph = 'BtEn'
####################################################################################
#Test
message = 'Bouncey bouncey!  Bouncey bouncey!'
              
